version: '3'

services:
  nginx:
    image: nginx:1.21
    container_name: nginx_lb
    restart: on-failure
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "4088:80"
      - "4098:8080"
    networks:
      - proxy_network

  app-1:
    container_name: api-to-db-1
    image: rash77/api-to-db:v0.0.1
    env_file: 
      - .env
    ports:
      - '8001:8000'
    restart: "no"
    networks:
      - proxy_network

  app-2:
    container_name: api-to-db-2
    image: rash77/api-to-db:v0.0.1
    env_file: 
      - .env
    ports:
      - '8002:8000'
    restart: "no"
    networks:
      - proxy_network

networks:
  proxy_network:
    name: mysql_net
    external: true
